export const allPayouts = [
  {
    amount: "₦900,000",
    status: "Successful",
    desc: "Payout INV-001",
    customer: "Olumide Ademola Babajide",
    paymentMethod: "Bank Transfer",
    date: "Dec 30, 09:42 PM",
  },
  {
    amount: "₦250,000",
    status: "Pending",
    desc: "Payout INV-002",
    customer: "Aisha Bello",
    paymentMethod: "Card",
    date: "Jan 2, 11:15 AM",
  },
  {
    amount: "₦500,000",
    status: "Refunded",
    desc: "Payout INV-003",
    customer: "Chinedu Okafor",
    paymentMethod: "Bank Transfer",
    date: "Jan 5, 03:20 PM",
  },
  {
    amount: "₦120,000",
    status: "Failed",
    desc: "Payout INV-004",
    customer: "Fatima Yusuf",
    paymentMethod: "Card",
    date: "Jan 7, 08:45 AM",
  },
  {
    amount: "₦1,200,000",
    status: "Successful",
    desc: "Payout INV-005",
    customer: "Emeka Nwosu",
    paymentMethod: "Bank Transfer",
    date: "Jan 10, 02:30 PM",
  },
  {
    amount: "₦350,000",
    status: "Pending",
    desc: "Payout INV-006",
    customer: "Grace Adeniyi",
    paymentMethod: "Card",
    date: "Jan 12, 10:00 AM",
  },
  {
    amount: "₦800,000",
    status: "Refunded",
    desc: "Payout INV-007",
    customer: "Kabiru Musa",
    paymentMethod: "Bank Transfer",
    date: "Jan 14, 04:10 PM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
  {
    amount: "₦75,000",
    status: "Failed",
    desc: "Payout INV-008",
    customer: "Ngozi Eze",
    paymentMethod: "Card",
    date: "Jan 15, 09:00 AM",
  },
  {
    amount: "₦600,000",
    status: "Successful",
    desc: "Payout INV-009",
    customer: "Samuel Johnson",
    paymentMethod: "Bank Transfer",
    date: "Jan 17, 01:25 PM",
  },
  {
    amount: "₦400,000",
    status: "Pending",
    desc: "Payout INV-010",
    customer: "Bola Ajayi",
    paymentMethod: "Card",
    date: "Jan 18, 11:40 AM",
  },
];

export const successfulPayouts = allPayouts.filter((p) => p.status === "Successful");
export const pendingPayouts = allPayouts.filter((p) => p.status === "Pending");
export const refundedPayouts = allPayouts.filter((p) => p.status === "Refunded");
export const failedPayouts = allPayouts.filter((p) => p.status === "Failed");